name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ejecucion de las pruebas unitarias
        run: npm install && npm run test  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "promotions-walmart-api" #Must be unique in Heroku
          heroku_email: "jstevenyepes@gmail.com"
          usedocker: true